// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALckppeawbhD6lIMQYJXgHhAFNO_cz5zU',
    appId: '1:62447984746:web:cab1b07829d4cf60816a13',
    messagingSenderId: '62447984746',
    projectId: 'flash-chat-f61a2',
    authDomain: 'flash-chat-f61a2.firebaseapp.com',
    storageBucket: 'flash-chat-f61a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY7RqaOsCssAIccy-8totga4CM6ScEozs',
    appId: '1:62447984746:android:beb87596d33f83fe816a13',
    messagingSenderId: '62447984746',
    projectId: 'flash-chat-f61a2',
    storageBucket: 'flash-chat-f61a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wN0oZ7I8zbCnFqzxmowCT1iYxZeKEpQ',
    appId: '1:62447984746:ios:7526c2aac8d0530b816a13',
    messagingSenderId: '62447984746',
    projectId: 'flash-chat-f61a2',
    storageBucket: 'flash-chat-f61a2.firebasestorage.app',
    iosBundleId: 'com.example.section15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9wN0oZ7I8zbCnFqzxmowCT1iYxZeKEpQ',
    appId: '1:62447984746:ios:7526c2aac8d0530b816a13',
    messagingSenderId: '62447984746',
    projectId: 'flash-chat-f61a2',
    storageBucket: 'flash-chat-f61a2.firebasestorage.app',
    iosBundleId: 'com.example.section15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALckppeawbhD6lIMQYJXgHhAFNO_cz5zU',
    appId: '1:62447984746:web:88f51a86e8528190816a13',
    messagingSenderId: '62447984746',
    projectId: 'flash-chat-f61a2',
    authDomain: 'flash-chat-f61a2.firebaseapp.com',
    storageBucket: 'flash-chat-f61a2.firebasestorage.app',
  );
}
